-- CONFIG --

-- Blacklisted weapons
weaponblacklist = {
  "WEAPON_HAMMER",
  "WEAPON_CROWBAR",
  "WEAPON_ADVANCEDRIFLE",
  "WEAPON_CARBINERIFLE_MK2",
  "WEAPON_GRENADELAUNCHER",
  "WEAPON_GRENADELAUNCHER_SMOKE",
  "WEAPON_RPG",
  "WEAPON_STINGER",
  "WEAPON_MINIGUN",
  "WEAPON_GRENADE",
  "WEAPON_BALL",
  "WEAPON_BOTTLE",
  "WEAPON_GUSENBERG",
  "WEAPON_SPECIALCARBINE",
  "WEAPON_BULLPUPRIFLE",
  "WEAPON_DAGGER",
  "WEAPON_MUSKET",
  "WEAPON_HEAVYSHOTGUN",
  "WEAPON_MARKSMANRIFLE",
  "WEAPON_FLAREGUN",
  "WEAPON_GARBAGEBAG",
  "WEAPON_RAILGUN",
}