print("^2 [MIXAS AntiCheat] ^5 EntityConfig Refresh ^0")
EntityConfig = {}

EntityConfig.Commands = {
    EntityDeleteCommand = 'entitywipe', -- you can use this command in F8, chat or CMD
    CarDeleteCommand = 'carwipe', -- you can use this command in F8, chat or CMD
    PedDeleteCommand = 'pedwipe', -- you can use this command in F8, chat or CMD
}

EntityConfig.VehicleLimits = {
    VSL = true, -- it blocks cheater to spawn so many vehicles, if you have NPCs in your server make it false
    VehicleSpawnLimit = 4, -- limit number for VSL
    VSLDebug = false, -- when someone spawns vehicles more than limitation you will see it in CMD
}

EntityConfig.PedLimits = {
    PSL = true, -- it blocks cheater to spawn so many peds or NPCs, if you have NPCs in your server make it false
    PedSpawnLimit = 4, -- limit number for PSL
    PSLDebug = false -- when someone spawns peds or NPCs more than limitation you will see it in CMD
}

EntityConfig.EntityLimits = {
    ESL = true, -- it blocks cheater to spawn so many objects
    EntitySpawnLimit = 2, -- limit number for ESL
    ESLDebug = false -- when someone spawns objects more than limitation you will see it in CMD
}

EntityConfig.Invisible = {
    Detection = true, -- if true, it removes everything invisible(vehicles, props/objetcs etc.)
    Ban = false, -- if true, it bans whoever spawns something invisible
    Kick = false -- if true, it kicks whoever spawns something invisible
}


EntityConfig.BlacklistEntities = {
    BlacklistEntity = true, -- if true, it detects blacklisted entites below
    BlacklistEntityBan = true, --if true, it bans when whoever spawns entites below
    BlacklistedEntity = {
        GetHashKey("cargoplane"),
        GetHashKey("avenger"),
        GetHashKey("avenger2"),
        GetHashKey("luxor"),
        GetHashKey("khanjali"),
        GetHashKey("prop_fnclink_05crnr1"),
        GetHashKey("xs_prop_hamburgher_wl"),
        GetHashKey("xs_prop_plastic_bottle_wl"),
        GetHashKey("prop_windmill_01"),
        GetHashKey("p_spinning_anus_s"),
        GetHashKey("stt_prop_ramp_adj_flip_m"),
        GetHashKey("stt_prop_ramp_adj_flip_mb"),
        GetHashKey("stt_prop_ramp_adj_flip_s"),
        GetHashKey("stt_prop_ramp_adj_flip_sb"),
        GetHashKey("stt_prop_ramp_adj_hloop"),
        GetHashKey("stt_prop_ramp_adj_loop"),
        GetHashKey("stt_prop_ramp_jump_l"),
        GetHashKey("stt_prop_ramp_jump_m"),
        GetHashKey("stt_prop_ramp_jump_s"),
        GetHashKey("stt_prop_ramp_jump_xl"),
        GetHashKey("stt_prop_ramp_jump_xs"),
        GetHashKey("stt_prop_ramp_jump_xxl"),
        GetHashKey("stt_prop_ramp_multi_loop_rb"),
        GetHashKey("stt_prop_ramp_spiral_l"),
        GetHashKey("stt_prop_ramp_spiral_l_l"),
        GetHashKey("stt_prop_ramp_spiral_l_m"),
        GetHashKey("stt_prop_ramp_spiral_l_s"),
        GetHashKey("stt_prop_ramp_spiral_l_xxl"),
        GetHashKey("stt_prop_ramp_spiral_m"),
        GetHashKey("stt_prop_ramp_spiral_s"),
        GetHashKey("stt_prop_ramp_spiral_xxl"),
        GetHashKey("stt_prop_stunt_track_dwuturn"),
        GetHashKey("stt_prop_stunt_track_dwslope30"),
        GetHashKey("stt_prop_stunt_track_start"),
        GetHashKey("stt_prop_stunt_track_hill2"),
        GetHashKey("stt_prop_stunt_bblock_huge_01"),
        GetHashKey("stt_prop_stunt_bblock_huge_02"),
        GetHashKey("stt_prop_stunt_bblock_huge_03"),
        GetHashKey("stt_prop_stunt_bblock_huge_04"),
        GetHashKey("stt_prop_stunt_bblock_huge_05"),
        GetHashKey("stt_prop_stunt_bblock_hump_01"),
        GetHashKey("stt_prop_stunt_bblock_hump_02"),
        GetHashKey("stt_prop_stunt_bblock_lrg1"),
        GetHashKey("stt_prop_stunt_bblock_lrg2"),
        GetHashKey("stt_prop_stunt_bblock_lrg3"),
        GetHashKey("stt_prop_stunt_bblock_mdm1"),
        GetHashKey("stt_prop_stunt_bblock_mdm2"),
        GetHashKey("stt_prop_stunt_bblock_mdm3"),
        GetHashKey("stt_prop_stunt_bblock_qp"),
        GetHashKey("stt_prop_stunt_bblock_qp2"),
        GetHashKey("stt_prop_stunt_bblock_qp3"),
        GetHashKey("prop_beach_fire"),
        GetHashKey("prop_gas_pump_1a"),
        GetHashKey("prop_gas_pump_1b"),
        GetHashKey("prop_gas_pump_1c"),
        GetHashKey("prop_gas_pump_1d"),
        GetHashKey("prop_gas_pump_old2"),
        GetHashKey("prop_gas_pump_old3"),
        GetHashKey("prop_vintage_pump"),
        GetHashKey("apa_mp_h_acc_box_trinket_01"),
        GetHashKey("prop_roundbailer02"),
        GetHashKey("prop_roundbailer01"),
        GetHashKey("prop_container_05a"),
        GetHashKey("stt_prop_stunt_bowling_ball"),
        GetHashKey("apa_mp_h_acc_rugwoolm_03"),
        GetHashKey("prop_container_ld2"),
        GetHashKey("p_ld_stinger_s"),
        GetHashKey("hei_prop_carrier_cargo_02a"),
        GetHashKey("p_cablecar_s"),
        GetHashKey("p_ferris_car_01"),
        GetHashKey("prop_cj_big_boat"),
        GetHashKey("prop_rock_4_big2"),
        GetHashKey("prop_steps_big_01"),
        GetHashKey("v_ilev_lest_bigscreen"),
        GetHashKey("prop_carcreeper"),
        GetHashKey("apa_mp_h_bed_double_09"),
        GetHashKey("apa_mp_h_bed_wide_05"),
        GetHashKey("prop_cattlecrush"),
        GetHashKey("prop_cs_documents_01"),
        GetHashKey("prop_ferris_car_01_lod1"),
        GetHashKey("prop_construcionlamp_01"),
        GetHashKey("prop_fncconstruc_01d"),
        GetHashKey("prop_fncconstruc_02a"),
        GetHashKey("p_dock_crane_cabl_s"),
        GetHashKey("prop_dock_crane_01"),
        GetHashKey("prop_dock_crane_02_cab"),
        GetHashKey("prop_dock_float_1"),
        GetHashKey("prop_dock_crane_lift"),
        GetHashKey("apa_mp_h_bed_double_08"),
        GetHashKey("csx_seabed_bldr4_"),
        GetHashKey("imp_prop_impexp_sofabed_01a"),
        GetHashKey("apa_mp_h_yacht_bed_01"),
        GetHashKey("rhino"),
        GetHashKey("insurgent"),
        GetHashKey("insurgent3"),
        GetHashKey("oppressor"),
        GetHashKey("oppressor2"),
        GetHashKey("blimp2"),
        GetHashKey("dingy"),
        GetHashKey("blimp3"),
        GetHashKey("freight"),
        GetHashKey("dump"),
        GetHashKey("a_m_y_acult_02"),
        GetHashKey("freightcar"),
        GetHashKey("limo2"),
        GetHashKey("freightcont1"),
        GetHashKey("freightcont2"),
        GetHashKey("freightgrain"),
        GetHashKey("cerberus3"),
        GetHashKey("cerberus2"),
        GetHashKey("cerberus"),
        GetHashKey("phantom2"),
        GetHashKey("issi6"),
        GetHashKey("issi4"),
        GetHashKey("issi5"),
        GetHashKey("savage"),
        GetHashKey("hunter"),
        GetHashKey("akula"),
        GetHashKey("annihilator"),
        GetHashKey("cutter"),
        GetHashKey("barracks3"),
        GetHashKey("barrage"),
        GetHashKey("chernobog"),
        GetHashKey("halftrack"),
        GetHashKey("minitank"),
        GetHashKey("scarab"),
        GetHashKey("scarab2"),
        GetHashKey("scarab3"),
        GetHashKey("thruster"),
        GetHashKey("trailersmall2"),
        GetHashKey("brutus3"),
        GetHashKey("freecrawler"),
        GetHashKey("monster"),
        GetHashKey("monster3"),
        GetHashKey("monster4"),
        GetHashKey("monster5"),
        GetHashKey("technical"),
        GetHashKey("technical3"),
        GetHashKey("technical2"),
        GetHashKey("nightshark"),
        GetHashKey("zhaba"),
        GetHashKey("formula"),
        GetHashKey("formula2"),
        GetHashKey("scramjet"),
        GetHashKey("vestra"),
        GetHashKey("velum"),
        GetHashKey("velum2"),
        GetHashKey("duster"),
        GetHashKey("trash2"),
        GetHashKey("coach"),
        GetHashKey("zr380"),
        GetHashKey("zr3802"),
        GetHashKey("zr3803"),
        GetHashKey("raptor"),
        GetHashKey("volatol"),
        GetHashKey("voltic2"),
        GetHashKey("tula"),
        GetHashKey("strikeforce"),
        GetHashKey("valkyrie2"),
        GetHashKey("valkyrie"),
        GetHashKey("jet"),
        GetHashKey("hydra"),
        GetHashKey("bombushka"),
        GetHashKey("bruiser3"),
        GetHashKey("bruiser2"),
        GetHashKey("bruiser"),
        GetHashKey("caracara"),
        GetHashKey("dune5"),
        GetHashKey("dune4"),
        GetHashKey("dune3"),
        GetHashKey("dune2"),
        GetHashKey("openwheel1"),
        GetHashKey("paragon2"),
        GetHashKey("formula"),
        GetHashKey("formula2"),
        GetHashKey("blazer5"),
        GetHashKey("slamvan4"),
        GetHashKey("slamvan5"),
        GetHashKey("slamvan6"),
        GetHashKey("ruiner2"),
        GetHashKey("dukes2"),
        GetHashKey("dominator4"),
        GetHashKey("dominator5"),
        GetHashKey("dominator6"),
        GetHashKey("handler"),
        GetHashKey("vindicator"),
        GetHashKey("wastelander"),
        GetHashKey("ardent"),
        -1404869155,--FIB Build
        -685641702, --unknown
        -759902142, --fire
        2967811882, --city
        566160949, --city
        841438406, --city
        3821613641,--city
        3957771795,--city
    }
}

EntityConfig.Deletes = {
    AllPedDelete = false, -- it deletes all peds
    AllPropDelete = false, -- it deletes all props
    AllCarDelete = false, -- it deletes all vehicles
}

EntityConfig.WhitelistEntitys = {
    PropWhitelist = false, -- if true, you can whitelist entities below so everyone will be able to use/spawn it
    PropKick = false,
    PropBan = false,
    WLProps = { -- here you can add or remove whitelisted objects
        1760825203,
        3258159972,
        3420629148,
        2518469636,
        386059801,
        2322124445,
        3182194296,
        0,
        3792764623,
        4078088296,
        4238628018,
        45840177,
        3646908049,
        1158698200,
        2724401750,
        3553022755,
        2366942797,
        3292998251,
        1302435108,
        3362210457,
        3745732117,
        3577824813,
        1020618269,
        2009246193,
        -1354005816,
        683570518,
        -2054442544,
        746336278,
        1874679314,
        1676901836,
        -1109340972,
        1847598393,
        -969349845,
        -1528307545,
        -708789241,
        76092178,
        61087258,
        -645296272,
        -1016640704,
        680380202,
        944959446,
        -517243780,
        -1170050911,
        -692093509,
        -917746868,
        1203231469,
        -461945070,
        -1623189257,
        -1585232418,
        1407197773,
        -678752633,
        -960996301,
        -1863407086,
        880595258,
        -447760697,
        600913159,
        1217034051,
        1471171713,
        -1296547421,
        1407268736,
        4117863282,
        765087784,
        1039360035,
        1336576410,
        -1249748547,
        -994740387,
        272925894,
        -781595832,
        -1676901836,
        -177104014,
        -741944541,
        -1972842851,
        1792816905,
        1603932804,
        3872089630,
        -746954904,
        -874338148,
        -113902346,
        250374685,
        686990798,
        463086472, 
        29402038,
        2017086435, 
        -598185919,  
        1368637848,
        1760825203,
        -74194454,
    }
}

