ConfigCS = {}
ConfigCS.Locale = 'en'

----//Your DISCORD-LOGS//----
ConfigCS.GlobalBan         = ""
ConfigCS.LOGS              = ""

----//Permission System, DO NOT TOUCH IF YOU DON'T KNOW WHAT ARE U DOING//----
ConfigCS.Bypass            = {"REAPER-Admin","REAPER-Mod"}
ConfigCS.OpenMenuAllowed   = {"REAPER-Admin"}
ConfigCS.SpectateAllowed   = {"REAPER-Admin","REAPER-Mod"}
ConfigCS.ClearAreaAllowed  = {"REAPER-Admin"}


----//Trigger Event prevention//----
ConfigCS.lynx = {
	"redst0nia:checking",
	"gcPhone:_internalAddMessage",
	"gcPhone:tchat_channel",
	"esx_vehicleshop:setVehicleOwned",
	"esx_mafiajob:confiscatePlayerItem",
	"lscustoms:payGarage",
	"vrp_slotmachine:server:2",
	"Banca:deposit",
	"bank:deposit",
	"esx_jobs:caution",
	"give_back",
	"SEM_InteractionMenu:Cuff:",
	"esx_fueldelivery:pay",
	"esx_carthief:pay",
	"esx_godirtyjob:pay",
	"esx_pizza:pay",
	"esx_ranger:pay",
	"esx_garbagejob:pay",
	"esx_truckerjob:pay",
	"AdminMenu:giveBank",
	"AdminMenu:giveCash",
	"esx_gopostaljob:pay",
	"esx_banksecurity:pay",
	"esx_slotmachine:sv:2",
	"esx:giveInventoryItem",
	"NB:recruterplayer",
	"esx_billing:sendBill",
	"esx_jailer:sendToJail",
	"esx_jail:sendToJail",
	"js:jailuser",
	"esx-qalle-jail:jailPlayer",
	"esx_dmvschool:pay", 
	"LegacyFuel:PayFuel",
	"OG_cuffs:cuffCheckNearest",
	"CheckHandcuff",
	"cuffServer",
	"cuffGranted",
	"police:cuffGranted",
	"SEM_InteractionMenu:Drag",
	"SEM_InteractionMenu:JailPlayer",
	"esx_handcuffs:cuffing",
	"esx_policejob:handcuff",
	"bank:withdraw",
	"dmv:success",
	"esx_skin:responseSaveSkin",
	"esx_dmvschool:addLicense",
	"esx_mechanicjob:startCraft",
	"esx_drugs:startHarvestWeed",
	"esx_drugs:startTransformWeed",
	"esx_drugs:startSellWeed",
	"esx_drugs:startHarvestCoke",
	"esx_drugs:startTransformCoke",
	"esx_drugs:startSellCoke",
	"esx_drugs:startHarvestMeth",
	"esx_drugs:startTransformMeth",
	"esx_drugs:startSellMeth",
	"esx_drugs:startHarvestOpium",
	"esx_drugs:startSellOpium",
	"esx_drugs:startTransformOpium",
	"esx_blanchisseur:startWhitening",
	"esx_drugs:stopHarvestCoke",
	"esx_drugs:stopTransformCoke",
	"esx_drugs:stopSellCoke",
	"esx_drugs:stopHarvestMeth",
	"esx_drugs:stopTransformMeth",
	"esx_drugs:stopSellMeth",
	"esx_drugs:stopHarvestWeed",
	"esx_drugs:stopTransformWeed",
	"esx_drugs:stopSellWeed",
	"esx_drugs:stopHarvestOpium",
	"esx_drugs:stopTransformOpium",
	"esx_drugs:stopSellOpium",
	"esx_society:openBossMenu",
	"esx_jobs:caution",
	"esx_tankerjob:pay",
	"esx_vehicletrunk:giveDirty",
	"gambling:spend",
	"AdminMenu:giveDirtyMoney",
	"esx_moneywash:deposit",
	"esx_moneywash:withdraw",
	"mission:completed",
	"truckerJob:success",
	"99kr-burglary:addMoney",
	"esx_jailer:unjailTime",
	"esx_ambulancejob:revive",
	"DiscordBot:playerDied",
	"hentailover:xdlol",
	"antilynx8:anticheat",
	"antilynxr6:detection",
	"esx:getSharedObject",
	"esx_society:getOnlinePlayers",
	"_chat:messageEntered",
	"antilynx8r4a:anticheat",
	"antilynxr4:detect",
	"js:jailuser", 
	"ynx8:anticheat",
	"lynx8:anticheat",
	"adminmenu:allowall",
	"h:xd",
	"ljail:jailplayer",
	"adminmenu:setsalary",
	"adminmenu:cashoutall",
	"bank:transfer",
	"paycheck:bonus",
	"paycheck:salary",
	"HCheat:TempDisableDetection",
	"esx_drugs:pickedUpCannabis",
	"esx_drugs:processCannabis",
	"esx-qalle-hunting:reward",
	"esx-qalle-hunting:sell",
	"esx_mecanojob:onNPCJobCompleted",
	"BsCuff:Cuff696999",
	"veh_SR:CheckMoneyForVeh",
	"esx_carthief:alertcops",
	"mellotrainer:adminTempBan",
	"mellotrainer:adminKick",
	"esx_society:putVehicleInGarage",
}

----//Anti Injection stuff//----
ConfigCS.lol = {
	'Desudo',
	'Brutan',
	'EulenCheats',
	"Lynx 8",
	"www.lynxmenu.com",
	"HamHaxia",
	"Ham Mafia",
	"www.renalua.com",
	"Fallen#0811",
	"Rena 8",
	"HamHaxia",
	"Ham Mafia",
	"Xanax#0134",
	">:D Player Crash",
	"34ByTe Community",
	"lynxmenu.com",
	"Anti-Lynx",
	"Baran#8992",
	"iLostName#7138",
	"85.190.90.118",
	"hammafia.com",
	"AlphaV ~ 5391",
	"vjuton.pl",
	"EulenCheat",
	"Eulen",
	"lynxmenu",
	"Lynx",
	"lynxmenu.com - Cheats & Anti-Cheats!",
	"Soviet Bear",
}

ConfigCS.ExplosionsList = {
    [1] = { name = "GrenadeLauncher", log = true, ban = true },
    [3] = { name = "Molotov", log = true, ban = true },
    [4] = { name = "Rocket", log = true, ban = true },
    [5] = { name = "TankShell", log = true, ban = true},
    [6] = { name = "Hi_Octane", log = false, ban = false },
    [7] = { name = "Car", log = false, ban = false },
    [8] = { name = "Plance", log = false, ban = false },
    [9] = { name = "PetrolPump", log = false, ban = false },
    [10] = { name = "Bike", log = false, ban = false },
    [11] = { name = "Dir_Steam", log = false, ban = false },
    [12] = { name = "Dir_Flame", log = false, ban = false },
    [13] = { name = "Dir_Water_Hydrant", log = false, ban = false },
    [14] = { name = "Dir_Gas_Canister", log = false, ban = false },
    [15] = { name = "Boat", log = false, ban = false },
    [16] = { name = "Ship_Destroy", log = false, ban = false },
    [17] = { name = "Truck", log = false, ban = false },
    [18] = { name = "Bullet", log = true, ban = true },
    [19] = { name = "SmokeGrenadeLauncher", log = true, ban = true },
    [20] = { name = "SmokeGrenade", log = false, ban = false },
    [21] = { name = "BZGAS", log = false, ban = false },
    [22] = { name = "Flare", log = false, ban = false },
    [23] = { name = "Gas_Canister", log = false, ban = false },
    [24] = { name = "Extinguisher", log = false, ban = false },
    [25] = { name = "Programmablear", ban = false },
    [26] = { name = "Train", log = false, ban = false },
    [27] = { name = "Barrel", log = false, ban = false },
    [28] = { name = "PROPANE", log = false, ban = false },
    [29] = { name = "Blimp", log = false, ban = false },
    [30] = { name = "Dir_Flame_Explode", log = false, ban = false },
    [31] = { name = "Tanker", log = false, ban = false },
    [32] = { name = "PlaneRocket", log = true, ban = true },
    [33] = { name = "VehicleBullet", ban = false },
    [34] = { name = "Gas_Tank", log = false, ban = false },
    [35] = { name = "FireWork", log = false, ban = false },
    [36] = { name = "SnowBall", log = false, ban = false },
    [37] = { name = "ProxMine", log = true, ban = true },
    [38] = { name = "Valkyrie_Cannon", log = true, ban = true }
}