clientconfig = {}

clientconfig.screen = {
    Freecamcheck = false,
    AntiPlayerBlips = true,
    AntiNightVision = true,
    AntiThermalVision = true,
    AntiNUIDEVTools = true,
    AntiALTF4 = true,
    
}

clientconfig.player = {
    PlayerProtection = true,
    AntiScriptStop = true,
    AntiScriptStart = true,
    AntiSuperJump = true,
    AntiSpectate = true,
    AntiNoClip = true,
    Maxplayerhealth = 200,
    AntiGodMode = true,
    AntiInvisble = true,
    AntinonRagdoll = true,
    AntiInfiniteStamina = true,
    AntiExplosiveBullet = true,

    AntiArmor = true,
    MaxArmor = 100,

}



clientconfig.Weapons = {
    AntiBlacklistedWeapons = false,
    AntiBlacklistedWeaponsBan = false,

    BLWeapons = {
        'WEAPON_RAILGUN',
        "WEAPON_RPG",
    }
}


clientconfig.ingame = {
    allwaysgamecheck = true,  --This thing resets every player if he uses a godmode bug, infinite ammo bug etc.
    allwayswipedestroyedcars = true,
    
    AntiCheatEngine = true,
}

clientconfig.Cars = {
    Antivehiclespawnblplate = true,
    BLCarsBan = true,

    blacklistedplates = {
        "Hammafia",
        "Eulen",
        "Blood-X",
        "obl2",
        "NUKE",
        "nuked",
        "Falcon",
        "Brutan",
        "Brutan#7799",
        "BRUTAN",
        "AKTeam",
        "LynxMenu",
        "TITOModz",
        "HamHaxia",
        "LYNX"
    },

    BLCars = {
        "khanjali",
        "rhino",
        "scarab2",	 
        "scarab3",	
        "cablecar",
        "scarab",	
        "trailersmall2",	
        "minitank",	
        "scarab2",	
        "valkyrie",
        "Cerberus",
        "blimp3",
        "blimp4",
        "blimp5",
        "hydra",
        "lazer",
        "savage",
        "Hunter",
        "Oppressor",
        "blimp2",
        "avenger",
        "bombushka",
        "armytanker",
        "armytrailer",
        "armytrailer2",
        "docktrailer",
        "freighttrailer",
        "graintrailer",
        "roptrailer",
        "raketrailer",
        "tr2",
        "tr4",
        "trflat",
        "tvtrailer",
        "tanker",
        "tanker2",
        "trailerlarge",
        "trailerlogs",
        "trailersmall",
        "trailers",
        "trailers2",
        "trailers3",
        "trailers4",
        "freightcar",
        "freight",
        "freightcont1",
        "freightcont2",
        "reightgrain",
        "metrotrain",
        "tankercar",
        "thruster",
        "bulldozer",
        "cutter",
        "dump",
        "handler",
        "apc",
        "chernobog",	
        "trailers4",
        "molotok",
        "caracara",
        "airbus",
        "pyro",
        "nokota",
        "nightshark",
        "monster",
        "vigilante",
        "menacer",
        "nightshark",
        "rcbandito",
        "technical",
        "technical2",
        "technical3",
        "rrocket",
        "dominator6",
        "ruiner2",
        "ruiner3",
        "slamvan6",
        "tampa3",
        "bruiser3",
        "brutus3",
        "caracara",
        "dune2",
        "dune3",
        "dune4",
        "dune5",
        "insurgent",
        "insurgent3",
        "monster5",
        "menacer",
        "nightshark",
        "barrage",
        "patrolboat",
        "phantom2",
        "akula",
        "annihilator",
    }
}

clientconfig.Menu = {
    WordOnMenuDetection = true,

    BLWordsOnScreen = {
        "aimbot", "Hamafia", "troll", "esp", "trigger", "triggerbot", "rage bot", "fallout", "godmode", "god mode", "modmenu", "esx money", "give armor", "ragebot", "rapidfire", "fuck server", "freecam", "execute", "superjump", "noclip", "hack",
        "lynx", "absolute", "ckgangisontop", "lumia1", "ISMMENU", "HydroMenu", "TAJNEMENUMenu", "rootMenu", "Outcasts666", "WaveCheat", "NacroxMenu", "MarketMenu", "topMenu", "FlexSkazaMenu", "SidMenu", "Crown", "Lynx8", "LynxEvo", "Maestro",
        "Tiago", "Brutan", "redEngine", "Unex", "Eulen", "Tiago Menu", "Dopameme", "redMENU", "falcon", "Desudo", "Onion", "explode", "rape", "Ciao", "Anticheat", "Tapatio", "Particle", "Malossi", "Nisi", "ATG", "RedStonia",
        "Chocohax", "Inyection", "Inyected", "Dumper", "LUA Executor", "Executor", "Skid", "HamMafia", "HamHaxia", "Dopamine", "HoaX", "inSec", "Reaper", "Lux", "Event Blocker", "Cheats", "Cheat", "Destroyer", "Spectate", "Wallhack", "Exploit", "triggers", "crosshair", "Explosive",
        "Alokas66", "Hacking System!", "Online Players", "Panic Button", "Destroy Menu", "Self Menu", "Server IP", "Teleport To", "Give Single Weapon", "Airstrike Player", "Taze Player", "Toga", "Magneto", "Self Options", "NiggaMenu", "Updated dynamic triggers for", "Metrix Methods"
    },

    AntiBlackListCommands = true,
    BLCommands = {
        "chocolate",
        "haha",
        "lol",
        "panickey",
        "killmenu",
        "panik",
        "ssssss",
        "brutan",
        "panic",
        "brutanpremium",
        "hammafia",
        "purgemenu",
        "hamhaxia",
        "redstonia",
        "hoax",
        "desudo",
        "jd",
        "ham",
        "lua options",
        "God Mode",
        "Maestro",
        "FunCtionOk",
        "lynx9_fixed",
        "lynx",
        "FOriv gay",
        "TiagoModz#1478",
        "WarMenu",
        "tiago",
        "TiagoModz",
        "dopamine",
        "dopamina",
        "Fucked",
        "injected",
        "vRP",
        "Flyteam",
        "8888",
        "Nigteam",
        "TEAMM",
        "HAmMaxIa",
        "deleted due to u being a nigger",
        "Dopamine injected successfully",
        "parent menu doesn",
        "www.d0pamine.xyz",
        "d0pamine v1.1 by Nertigel",
        "d0pamine",
        "Nertigel: This server is protected and the menu is not gonna work here.", 
        "Information",
        "[dopamine]",
        "KP",
        "opk",
        "jolmany",
        "SovietH4X",
    }
}



